### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by ad-anssi** [ANSSI-FR/rust-guide#25]
Here is a complete list of current 'todo' mentions in the guide:

- [ ] Cargo features and environment variables (Chapter 2)
- [ ] Unsafe code in libraries (Chapter 3)
- [ ] Good practices for error handling (Chapter 4)
- [ ] no_panic crate (Chapter 4)
- [ ] Macros (Chapter 4)
- [ ] Memory management intro (Chapter 5)
- [ ] Rust type system pitfalls (Chapter 6)
- [ ] Foreign library in Rust, example (Chapter 7)
- [ ] Testing Rust code (Chapter 8)
- [ ] Fuzzing Rust code (Chapter 8)
